### PR TITLE
Implement `<FormProvider>`, remove `date-fns` and fix login modal bug

### LINKED ISSUE #90: Refactor: Use `react-form-hook`'s `<FormProvider>` instead of passing `control` to individual fields
# Background

Currently, we have this long-winded code for every form to pass the `name` and, more importantly, the `control` of the form to the `useController` hook of each field in the form.

```js
  const controllers: Controllers<RegisterFormModel> = {
    firstName: {
      control,
      name: 'firstName',
    },
    lastName: {
      control,
      name: 'lastName',
    },
    gender: {
      control,
      name: 'gender',
    },
    dob: {
      control,
      name: 'dob',
    },
    email: {
      control,
      name: 'email',
    },
    password: {
      control,
      name: 'password',
    },
  };
```

# Proposal

We can avoid passing the `control` of the form to individual fields by wrapping the form around a `<FormProvider>`  exported from `react-form-hook` (See the description of the `control` property in the [docs](https://react-hook-form.com/api/usecontroller)).

By doing this, we can eleminate the `controllers` altogether and pass only the `name` directly to the fields.

Official example for the use of `<FormProvider>` can be found [here](https://codesandbox.io/s/react-hook-form-form-context-2703c?file=/src/index.js:327-339).

### LINKED ISSUE #91: Remove date-fns
At the moment, `date-fns` is only used for formatting date in DatePickerInput. This should be easily replaced with `dayjs`. See https://react-day-picker.js.org/docs/input

https://github.com/Andrewnt219/rent-near-me/blob/945769289561acd6b5c98d87b88faeefef9a5ff8/src/libs/react-day-picker/DatePicker.tsx#L50-L51

### LINKED ISSUE #93: Login modal is closed on wrong credentials
## Reproduce
Branch: dev

- From homepage, open Menu > Login
- Enter the wrong username and password
- Press login

## What happened
The modal is closed

## Expect
Login should open and show an error message

---

I suspect this is because react-hook-form doesn't properly handle errors thrown in `handleSubmit`. I might have done it wrong, but their docs is not accurate. This does not handle the throw (even though their docs says so)
```
const onSubmit = () => {
  throw new Error('Something is wrong')
}

handleSubmit(onSubmit).catch((e) => {
  // you will need to catch that error
})
```

In the other project, [I handle this with mutation from react-query](https://github.com/Andrewnt219/seneca-course-reviews/blob/main/src/modules/auth/components/SignupForm/SignupForm.tsx). SWR seems to has the same concept for [mutation](https://swr.vercel.app/docs/mutation), but I'm not sure.

### PR DESCRIPTION
**Pull request by vitokhangnguyen**
Closes #90 
Closes #91 
Closes #93

### CODE REVIEW

File: src/modules/account/components/ChangePasswordForm/useChangePasswordForm.ts [hunk 1]
```diff
@@ -15,8 +14,9 @@ import { useActionField } from '@modules/account/contexts/ActionFieldContext';
 
 export const useChangePasswordForm = () => {
   const { t } = useTranslation();
-  const actionField = useActionField();
   const { user } = useAuth();
+  const [submitError, setSubmitError] = useState('');
```
Comment (Andrewnt219) [inline src/modules/account/components/ChangePasswordForm/useChangePasswordForm.ts:18]: initial state should be null

File: src/modules/account/components/ChangePasswordForm/useChangePasswordForm.ts [hunk 2]
```diff
@@ -15,8 +14,9 @@ import { useActionField } from '@modules/account/contexts/ActionFieldContext';
...
+  const actionField = useActionField();
```
Comment (Andrewnt219) [inline src/modules/account/components/ChangePasswordForm/useChangePasswordForm.ts:19]: Instead of this, which makes this component depends on ActionField, you can make an `onSubmit` inside ActionField and call the submit handler there instead.

File: src/modules/user-auth/components/LoginForm/useLoginForm.ts [hunk 3]
```diff
@@ -13,39 +12,19 @@ import { useLayoutModal } from '@modules/layouts/contexts/LayoutModalContext';
...
   const onSubmit = form.handleSubmit(async (data) => {
-    await AuthService.signInWithEmail(
-      data.email,
-      data.password,
-      data.keepLogIn
-    ).catch((err) => setSubmitError(err.error_description || err.message));
-
-    loginModal.hide();
+    AuthService.signInWithEmail(data.email, data.password, data.keepLogIn)
+      .then(() => loginModal.hide())
```
Comment (Andrewnt219) [inline src/modules/user-auth/components/LoginForm/useLoginForm.ts:25]: we can keep the `await` here.

File: src/modules/user-auth/components/RegisterForm/useRegisterForm.ts [hunk 4]
```diff
@@ -13,47 +13,19 @@ import { useForm } from 'react-hook-form';
 
 export default function useRegisterForm() {
   const { t } = useTranslation();
+  const { registerModal } = useLayoutModal();
+  const [submitError, setSubmitError] = useState('');
```
Comment (Andrewnt219) [inline src/modules/user-auth/components/RegisterForm/useRegisterForm.ts:17]: initiate with null

File: src/modules/user-auth/components/RegisterForm/useRegisterForm.ts [hunk 5]
```diff
@@ -13,47 +13,19 @@ import { useForm } from 'react-hook-form';
...
-      name: 'password',
-    },
-  };
 
   const onSubmit = form.handleSubmit(async (data) => {
-    await AuthService.registerWithEmail(data).catch((e) =>
-      setSubmitError(getErrorMessage(e, t))
-    );
+    AuthService.registerWithEmail(data)
+      .then(() => registerModal.hide())
```
Comment (Andrewnt219) [inline src/modules/user-auth/components/RegisterForm/useRegisterForm.ts:27]: use `await`

File: src/ui/Form/Checkbox.tsx [hunk 6]
```diff
@@ -53,11 +50,16 @@ export default function Checkbox<FormValues extends FieldValues>({
       </Form.CheckboxLabel>
 
       <Form.TextWrapper>
-        <Form.ErrorMessage id={id + 'error'}>
-          {fieldState.error?.message}
-        </Form.ErrorMessage>
-        <Form.Description>{inputDescription}</Form.Description>
+        {fieldState.invalid ? (
```
Comment (Andrewnt219) [inline src/ui/Form/Checkbox.tsx:53]: Even when there's an error, helper text should still be visible.

File: src/ui/Form/Checkbox.tsx [hunk 7]
```diff
@@ -42,7 +39,7 @@ export default function Checkbox<FormValues extends FieldValues>({
         />
         <Form.CheckboxTick
           role="checkbox"
-          aria-describedby={id + 'error'}
+          aria-describedby={fieldState.invalid ? errMsgId : descId}
```
Comment (Andrewnt219) [inline src/ui/Form/Checkbox.tsx:42]: `aria-describedBy` can be used with multiple labels.

See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

File: src/ui/Form/DateField.tsx [hunk 8]
```diff
@@ -47,28 +48,32 @@ function DatePicker<FormValues extends FieldValues>({
         // onDayChange won't work with user keyboard's input
         dayPickerProps={{ ...dayPickerProps, onDayClick: field.onChange }}
         placeholder=" "
-        formatDate={formatDate}
-        parseDate={parseDate}
+        formatDate={(date, format) => dayjs(date).format(format)}
```
Comment (Andrewnt219) [inline src/ui/Form/DateField.tsx:51]: can you define these as functions first and call them here?

File: src/ui/Form/DateField.tsx [hunk 9]
```diff
@@ -47,28 +48,32 @@ function DatePicker<FormValues extends FieldValues>({
...
         {label}
       </StyledLabel>
 
       <Form.TextWrapper>
-        {fieldState.invalid && (
-          <Form.ErrorMessage>{fieldState.error?.message}</Form.ErrorMessage>
-        )}
-        {!fieldState.invalid && (
-          <Form.Description>{inputDescription}</Form.Description>
+        {fieldState.invalid ? (
```
Comment (Andrewnt219) [inline src/ui/Form/DateField.tsx:66]: Same as checkbox, helper text should be visible.

File: src/ui/Form/PasswordField.tsx [hunk 10]
```diff
@@ -1,41 +1,40 @@
...
+  const errMsgId = useMemo(() => `error-${id}`, [id]);
+  const descId = useMemo(() => `description-${id}`, [id]);
 
   return (
     <Form.Group>
       <div tw="relative">
         <Form.Input
-          aria-describedby={`error-${props.id}`}
+          id={id}
+          aria-describedby={`description-${id}`}
```
Comment (Andrewnt219) [inline src/ui/Form/PasswordField.tsx:37]: Same as Checkbox. Multiple values.

File: src/ui/Form/PasswordField.tsx [hunk 11]
```diff
@@ -55,16 +54,16 @@ function PasswordField<FormValues extends FieldValues>(
       </div>
 
       <Form.TextWrapper>
-        {fieldState.invalid && (
-          <Form.ErrorMessage id={`error-${props.id}`}>
+        {fieldState.invalid ? (
```
Comment (Andrewnt219) [inline src/ui/Form/PasswordField.tsx:57]: Same as Checkbox. Helper text should be visible.

File: src/ui/Form/Select.tsx [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+
+  const errMsgId = useMemo(() => `error-${id}`, [id]);
+  const descId = useMemo(() => `description-${id}`, [id]);
+
+  return (
+    <Form.Group>
+      <Form.Select
+        id={id}
+        aria-invalid={fieldState.invalid}
+        aria-describedby={fieldState.invalid ? errMsgId : descId}
```
Comment (Andrewnt219) [inline src/ui/Form/Select.tsx:34]: Same as Checkbox. Multiple values.

File: src/ui/Form/Select.tsx [hunk 13]
```diff
@@ -0,0 +1,59 @@
...
+        data-selected={value.toString() !== ''}
+      >
+        {children}
+      </Form.Select>
+
+      <Form.Label htmlFor={id}>{label}</Form.Label>
+      <GoChevronDown tw="absolute top-lg right-md" />
+
+      <Form.TextWrapper>
+        {fieldState.invalid ? (
```
Comment (Andrewnt219) [inline src/ui/Form/Select.tsx:47]: Same as Checkbox. Visible helper text.

File: src/ui/Form/TextField.tsx [hunk 14]
```diff
@@ -1,52 +1,54 @@
...
+
+  const errMsgId = useMemo(() => `error-${id}`, [id]);
+  const descId = useMemo(() => `description-${id}`, [id]);
 
   return (
     <Form.Group>
       <Form.Input
-        aria-describedby={`error-${inputProps.id}`}
+        id={id}
+        aria-describedby={fieldState.invalid ? errMsgId : descId}
```
Comment (Andrewnt219) [inline src/ui/Form/TextField.tsx:31]: Same as Checkbox.

File: src/ui/Form/TextField.tsx [hunk 15]
```diff
@@ -1,52 +1,54 @@
...
         placeholder=" "
       />
 
-      <Form.Label htmlFor={inputProps.id}>{label}</Form.Label>
+      <Form.Label htmlFor={id}>{label}</Form.Label>
 
       <Form.TextWrapper>
-        {fieldState.invalid && (
-          <Form.ErrorMessage id={`error-${inputProps.id}`}>
+        {fieldState.invalid ? (
```
Comment (Andrewnt219) [inline src/ui/Form/TextField.tsx:42]: Same as Checkbox.

**Review by Andrewnt219 — CHANGES_REQUESTED** [review]
Excellent, this is more of the API I'm looking for. 

Lose the type-safe of the `name` but I'll take that over `controllers` any day.

File: src/modules/account/components/ChangePasswordForm/useChangePasswordForm.ts (hunk 2 above)
Comment (vitokhangnguyen) [reply src/modules/account/components/ChangePasswordForm/useChangePasswordForm.ts:19]: Same thing with the `LoginForm` and `RegisterForm` where we made them depend on the Modal instead. I think the general idea should be that any form component has `onSubmitSuccess` and `onSubmitError` prop.

Having `onSubmit` on the ActionField implies that ActionField is submitable which is not an expected behavior of the ActionField

File: src/modules/user-auth/components/LoginForm/useLoginForm.ts (hunk 3 above)
Comment (vitokhangnguyen) [reply src/modules/user-auth/components/LoginForm/useLoginForm.ts:25]: Nah, that is the source of the bug in the first place. I recommend not mixing `await` and `then/catch` anymore since it produces more complexity. Any logic can be performed after both `try` and `catch` can be done before that anyway since there's practically no difference now.

File: src/modules/user-auth/components/RegisterForm/useRegisterForm.ts (hunk 5 above)
Comment (vitokhangnguyen) [reply src/modules/user-auth/components/RegisterForm/useRegisterForm.ts:27]: Same as above, don't think we should do this

File: src/ui/Form/Checkbox.tsx (hunk 6 above)
Comment (vitokhangnguyen) [reply src/ui/Form/Checkbox.tsx:53]: This is not the behavior we're having the whole time and also not what Airbnb has

image

image

I actaully like this better

File: src/ui/Form/DateField.tsx (hunk 8 above)
Comment (vitokhangnguyen) [reply src/ui/Form/DateField.tsx:51]: It's just that defining them someone, I had to type the type annotations while no type annotation is needed if I defined it in place lol

File: src/ui/Form/DateField.tsx (hunk 9 above)
Comment (vitokhangnguyen) [reply src/ui/Form/DateField.tsx:66]: Same as [here](https://github.com/Andrewnt219/rent-near-me/pull/96#discussion_r743710763)

File: src/ui/Form/PasswordField.tsx (hunk 11 above)
Comment (vitokhangnguyen) [reply src/ui/Form/PasswordField.tsx:57]: Same as [here](https://github.com/Andrewnt219/rent-near-me/pull/96#discussion_r743710763)

File: src/ui/Form/Select.tsx (hunk 13 above)
Comment (vitokhangnguyen) [reply src/ui/Form/Select.tsx:47]: Same as [here](https://github.com/Andrewnt219/rent-near-me/pull/96#discussion_r743710763)

File: src/ui/Form/TextField.tsx (hunk 15 above)
Comment (vitokhangnguyen) [reply src/ui/Form/TextField.tsx:42]: Same as [here](https://github.com/Andrewnt219/rent-near-me/pull/96#discussion_r743710763)

File: src/modules/account/components/ChangePasswordForm/useChangePasswordForm.ts (hunk 2 above)
Comment (Andrewnt219) [reply src/modules/account/components/ChangePasswordForm/useChangePasswordForm.ts:19]: Oh wait, this is inside ChangePasswordForm, for some reason I thought this is a general component TextField. Reviewing code just after waking up be like.

File: src/modules/user-auth/components/LoginForm/useLoginForm.ts (hunk 3 above)
Comment (Andrewnt219) [reply src/modules/user-auth/components/LoginForm/useLoginForm.ts:25]: oh right, after it throws, it still goes on to the next line.

File: src/ui/Form/DateField.tsx (hunk 8 above)
Comment (Andrewnt219) [reply src/ui/Form/DateField.tsx:51]: Thought you're not a fan of verbose component props as well. Still, we don't define onClick inline so keep the consistency.

**Comment by Andrewnt219** [comment]
Never reviewing code half-awake again.

File: src/ui/Form/DateField.tsx (hunk 8 above)
Comment (vitokhangnguyen) [reply src/ui/Form/DateField.tsx:51]: I am not but people change at 3:30 am. Making the change

**Review by Andrewnt219 — APPROVED** [review]
